# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Codexo.ExoSnap
PackageVersion: 0.10.1
MinimumOSVersion: 10.0.17763.0
InstallerType: wix
Scope: machine
InstallModes:
- silent
- silentWithProgress
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Exoridus/exosnap/releases/download/v0.10.1/ExoSnap-0.10.1-windows-x64.msi
  InstallerSha256: 347A6F3D25289CC5322237A2814BA988E0AEF4BF93E1612B6D45EAB4FD7B2C3E
  ProductCode: '{8A863D0C-A7AF-4F44-8EBB-FB3AE41AE9F9}'
  AppsAndFeaturesEntries:
  - DisplayName: ExoSnap
    Publisher: Codexo
    DisplayVersion: 0.10.1
    ProductCode: '{8A863D0C-A7AF-4F44-8EBB-FB3AE41AE9F9}'
    UpgradeCode: '{8988DAFC-3AE4-4788-BA6D-62E3F73C7A7D}'
    InstallerType: wix
ManifestType: installer
ManifestVersion: 1.10.0
ReleaseDate: 2026-10-03
